name: Täglicher Notebook-Job um 21:00

on:
  schedule:
    - cron: '0 19 * * *'  # 19:00 UTC = 21:00 CH-Zeit
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Repository clonen
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Benötigte Pakete installieren
        run: pip install pandas paramiko

      - name: Notebook-Code ausführen
        run: python mein_notebook.py
